In [3]:
''' Q1. What is Min-Max scaling, and how is it used in data preprocessing? Provide an example to illustrate its
application'''

' Q1. What is Min-Max scaling, and how is it used in data preprocessing? Provide an example to illustrate its\napplication'

In [4]:
'''Min-Max Scaling:

Definition: Min-Max scaling, also known as normalization, is a data preprocessing technique that rescales features to a fixed range,
typically [0, 1]. It transforms each feature to a specific range by subtracting the minimum value and dividing by the range of the feature.
'''

'Min-Max Scaling:\n\nDefinition: Min-Max scaling, also known as normalization, is a data preprocessing technique that rescales features to a fixed range,\ntypically [0, 1]. It transforms each feature to a specific range by subtracting the minimum value and dividing by the range of the feature.\n'

In [5]:
Feature: [50, 60, 70, 80, 90]
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Example data
data = np.array([[50], [60], [70], [80], [90]])

# Create scaler
scaler = MinMaxScaler()

# Fit and transform data
scaled_data = scaler.fit_transform(data)
print(scaled_data)


[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


In [6]:
'''Q2. What is the Unit Vector technique in feature scaling, and how does it differ from Min-Max scaling?
Provide an example to illustrate its application.'''

'Q2. What is the Unit Vector technique in feature scaling, and how does it differ from Min-Max scaling?\nProvide an example to illustrate its application.'

In [7]:
'''Definition: Unit vector scaling, also known as normalization to unit length, rescales features so that the feature vector has a length of 1. 
This is done by dividing each feature value by the Euclidean norm (L2 norm) of the vector.'''

'Definition: Unit vector scaling, also known as normalization to unit length, rescales features so that the feature vector has a length of 1. \nThis is done by dividing each feature value by the Euclidean norm (L2 norm) of the vector.'

In [9]:
Feature : [3, 4]
import numpy as np
from sklearn.preprocessing import normalize

# Example data
data = np.array([[3, 4]])

# Normalize data to unit vector
normalized_data = normalize(data, norm='l2')
print(normalized_data)


[[0.6 0.8]]


In [10]:
'''Q3. What is PCA (Principle Component Analysis), and how is it used in dimensionality reduction? Provide an
example to illustrate its application'''

'Q3. What is PCA (Principle Component Analysis), and how is it used in dimensionality reduction? Provide an\nexample to illustrate its application'

In [11]:
'''Principal Component Analysis (PCA):

Definition: PCA is a dimensionality reduction technique that transforms data into a new coordinate system where the greatest variances by any projection of the data come to lie on the first coordinates called principal components. It reduces the number of dimensions while retaining most of the variance (information) in the data.

Usage in Dimensionality Reduction:

Reduce Complexity: By projecting data onto fewer dimensions, PCA simplifies the data while retaining essential patterns.
Improve Performance: It helps in speeding up machine learning algorithms and reducing overfitting by eliminating redundant features.'''


'Principal Component Analysis (PCA):\n\nDefinition: PCA is a dimensionality reduction technique that transforms data into a new coordinate system where the greatest variances by any projection of the data come to lie on the first coordinates called principal components. It reduces the number of dimensions while retaining most of the variance (information) in the data.\n\nUsage in Dimensionality Reduction:\n\nReduce Complexity: By projecting data onto fewer dimensions, PCA simplifies the data while retaining essential patterns.\nImprove Performance: It helps in speeding up machine learning algorithms and reducing overfitting by eliminating redundant features.'

In [12]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Example data: 3 features
data = np.array([[2, 3, 4],
                 [3, 6, 9],
                 [4, 8, 12],
                 [5, 10, 15],
                 [6, 12, 18]])

# Standardize the data
scaler = StandardScaler()
data_standardized = scaler.fit_transform(data)

# Apply PCA
pca = PCA(n_components=2)  # Reduce to 2 components
data_pca = pca.fit_transform(data_standardized)
print(data_pca)


[[ 2.60994863 -0.11396371]
 [ 1.05085985  0.126715  ]
 [-0.08470482  0.06123228]
 [-1.22026949 -0.00425043]
 [-2.35583416 -0.06973314]]


In [13]:
'''Q4. What is the relationship between PCA and Feature Extraction, and how can PCA be used for Feature
Extraction? Provide an example to illustrate this concept'''

'Q4. What is the relationship between PCA and Feature Extraction, and how can PCA be used for Feature\nExtraction? Provide an example to illustrate this concept'

In [14]:
'''Relationship between PCA and Feature Extraction:

PCA (Principal Component Analysis) is a specific technique used for feature extraction. Feature extraction involves transforming original features into a new set of features that are more informative or compact. PCA performs this transformation by creating new features (principal components) that capture the most variance in the data.

Using PCA for Feature Extraction:

Extract Principal Components: PCA finds the principal components (new features) that capture the maximum variance in the data.
Dimensionality Reduction: By selecting the top principal components, you reduce the number of features while retaining the most important information'''

'Relationship between PCA and Feature Extraction:\n\nPCA (Principal Component Analysis) is a specific technique used for feature extraction. Feature extraction involves transforming original features into a new set of features that are more informative or compact. PCA performs this transformation by creating new features (principal components) that capture the most variance in the data.\n\nUsing PCA for Feature Extraction:\n\nExtract Principal Components: PCA finds the principal components (new features) that capture the maximum variance in the data.\nDimensionality Reduction: By selecting the top principal components, you reduce the number of features while retaining the most important information'

In [15]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Example data with 4 features
data = np.array([[2, 3, 4, 5],
                 [4, 6, 8, 10],
                 [5, 7, 9, 12],
                 [6, 8, 11, 14],
                 [7, 9, 12, 15]])

# Standardize the data
scaler = StandardScaler()
data_standardized = scaler.fit_transform(data)

# Apply PCA to reduce to 2 features
pca = PCA(n_components=2)
data_reduced = pca.fit_transform(data_standardized)
print(data_reduced)


[[ 3.42425314  0.09433097]
 [ 0.69092637 -0.12384746]
 [-0.30404696 -0.05944936]
 [-1.47862934 -0.05622134]
 [-2.33250321  0.14518718]]


In [16]:
'''Q5. You are working on a project to build a recommendation system for a food delivery service. The dataset
contains features such as price, rating, and delivery time. Explain how you would use Min-Max scaling to
preprocess the data.'''

'Q5. You are working on a project to build a recommendation system for a food delivery service. The dataset\ncontains features such as price, rating, and delivery time. Explain how you would use Min-Max scaling to\npreprocess the data.'

In [17]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Example data
data = pd.DataFrame({
    'price': [10, 20, 30, 40, 50],
    'rating': [3.5, 4.0, 4.5, 5.0, 4.8],
    'delivery_time': [30, 25, 20, 15, 10]
})

# Create MinMaxScaler object
scaler = MinMaxScaler()

# Fit and transform the data
scaled_data = scaler.fit_transform(data)
scaled_df = pd.DataFrame(scaled_data, columns=data.columns)
print(scaled_df)


   price    rating  delivery_time
0   0.00  0.000000           1.00
1   0.25  0.333333           0.75
2   0.50  0.666667           0.50
3   0.75  1.000000           0.25
4   1.00  0.866667           0.00


In [18]:
'''Q6. You are working on a project to build a model to predict stock prices. The dataset contains many
features, such as company financial data and market trends. Explain how you would use PCA to reduce the
dimensionality of the dataset.'''

'Q6. You are working on a project to build a model to predict stock prices. The dataset contains many\nfeatures, such as company financial data and market trends. Explain how you would use PCA to reduce the\ndimensionality of the dataset.'

In [19]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Example data
data = pd.DataFrame({
    'revenue': [10, 20, 30, 40, 50],
    'profit': [1, 2, 3, 4, 5],
    'market_index': [1000, 1100, 1050, 1080, 1020],
    'trading_volume': [500, 600, 550, 580, 520]
})

# Standardize the data
scaler = StandardScaler()
data_standardized = scaler.fit_transform(data)
from sklearn.decomposition import PCA

# Apply PCA
pca = PCA(n_components=0.95)  # Retain 95% of variance
data_pca = pca.fit_transform(data_standardized)

# Create a DataFrame with the principal components
pca_df = pd.DataFrame(data_pca, columns=[f'PC{i+1}' for i in range(data_pca.shape[1])])
print(pca_df)


        PC1       PC2
0  2.770029 -0.058398
1 -0.648709 -2.062922
2 -0.000000  0.000000
3 -1.520596 -0.106382
4 -0.600724  2.227703


In [20]:
'''Q7. For a dataset containing the following values: [1, 5, 10, 15, 20], perform Min-Max scaling to transform the
values to a range of -1 to 1.'''

'Q7. For a dataset containing the following values: [1, 5, 10, 15, 20], perform Min-Max scaling to transform the\nvalues to a range of -1 to 1.'

In [22]:
import numpy as np

# Original data
data = np.array([1, 5, 10, 15, 20])

# Min-Max scaling to [0, 1]
min_val = np.min(data)
max_val = np.max(data)
scaled_data = (data - min_val) / (max_val - min_val)

# Transform to [-1, 1]
final_data = 2 * scaled_data - 1
print(final_data)


[-1.         -0.57894737 -0.05263158  0.47368421  1.        ]


In [23]:
'''Q8. For a dataset containing the following features: [height, weight, age, gender, blood pressure], perform
Feature Extraction using PCA. How many principal components would you choose to retain, and why?'''

'Q8. For a dataset containing the following features: [height, weight, age, gender, blood pressure], perform\nFeature Extraction using PCA. How many principal components would you choose to retain, and why?'

In [24]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Example data with features: height, weight, age, gender (encoded), blood pressure
data = pd.DataFrame({
    'height': [160, 170, 180, 190, 200],
    'weight': [55, 70, 85, 90, 95],
    'age': [25, 30, 35, 40, 45],
    'gender': [0, 1, 0, 1, 0],  # Example encoding: 0 for female, 1 for male
    'blood_pressure': [120, 130, 140, 150, 160]
})

# Standardize the data
scaler = StandardScaler()
data_standardized = scaler.fit_transform(data)

# Apply PCA
pca = PCA()
pca.fit(data_standardized)

# Explained variance ratio
explained_variance_ratio = pca.explained_variance_ratio_
cumulative_variance = np.cumsum(explained_variance_ratio)

# Number of components to retain
num_components = np.argmax(cumulative_variance >= 0.95) + 1  # Retain enough components to explain 95% variance
print(f'Number of principal components to retain: {num_components}')


Number of principal components to retain: 2
